/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import dominio.Cliente;
import dominio.CuentasClientesRecord;
import excepciones.PersistenciaException;
import interfaces.IClientesDAO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;

/**
 *
 * @author eruma
 */
public class Cuentas extends javax.swing.JFrame {

    private final IClientesDAO clientesDao;
    private final Cliente cliente;
    /**
     * Creates new form Cuentas
     */
    public Cuentas(IClientesDAO clientesDao, Cliente cliente) {
        initComponents();
        this.clientesDao = clientesDao;
        this.cliente=cliente;
        this.cargarCuentas();
    }

    public void cargarCuentas(){
        ComboBoxModel cob = this.cBoxCuentas.getModel();
        try {
            ArrayList<CuentasClientesRecord> cuentas = clientesDao.cargarCuentas(cliente.getId());
            for (int i = 0; i < cuentas.size(); i++) {
                if (cuentas.get(i) != null) {
                    this.cBoxCuentas.addItem(cuentas.get(i).nombre());
                }
            }
        } catch (PersistenciaException ex) {
            Logger.getLogger(Cuentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblSaldo1 = new javax.swing.JLabel();
        cBoxCuentas = new javax.swing.JComboBox<>();
        lblSaldo = new javax.swing.JLabel();
        lblCuentas = new javax.swing.JLabel();
        lblPestanaTransac = new javax.swing.JLabel();
        lblPestanaUser = new javax.swing.JLabel();
        lblPestanaCuenta = new javax.swing.JLabel();
        lblRecuadro = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuentas");
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCuentas/anadirCuenta.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        pnlFondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        lblSaldo1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblSaldo1.setForeground(new java.awt.Color(153, 153, 153));
        lblSaldo1.setText("saldoDelCliente");
        lblSaldo1.setFocusable(false);
        pnlFondo.add(lblSaldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 200, 30));

        cBoxCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxCuentasActionPerformed(evt);
            }
        });
        pnlFondo.add(cBoxCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 190, -1));

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(153, 153, 153));
        lblSaldo.setText("Saldo:");
        pnlFondo.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 70, 30));

        lblCuentas.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblCuentas.setForeground(new java.awt.Color(153, 153, 153));
        lblCuentas.setText("Cuenta:");
        pnlFondo.add(lblCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 70, 30));

        lblPestanaTransac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCuentas/penstana.png"))); // NOI18N
        pnlFondo.add(lblPestanaTransac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        lblPestanaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCuentas/penstana.png"))); // NOI18N
        pnlFondo.add(lblPestanaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        lblPestanaCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCuentas/penstana.png"))); // NOI18N
        pnlFondo.add(lblPestanaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblRecuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCuentas/recuadro.png"))); // NOI18N
        pnlFondo.add(lblRecuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.png"))); // NOI18N
        lblFondo.setAlignmentY(0.0F);
        lblFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxCuentasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cBoxCuentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCuentas;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPestanaCuenta;
    private javax.swing.JLabel lblPestanaTransac;
    private javax.swing.JLabel lblPestanaUser;
    private javax.swing.JLabel lblRecuadro;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
