/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import dominio.Cliente;
import dominio.CuentasClientesRecord;
import excepciones.PersistenciaException;
import interfaces.IClientesDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kim
 */
public class FrmRegistroCuentasBancarias extends javax.swing.JFrame {

    private final IClientesDAO clientesDao;
    private final Cliente cliente;

    /**
     * Creates new form FrmCuentasBancarias
     */
    public FrmRegistroCuentasBancarias(IClientesDAO clientesDao, Cliente cliente) {
        initComponents();
        this.clientesDao = clientesDao;
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblNombreCuenta = new javax.swing.JLabel();
        txtFieldNombreCuenta = new javax.swing.JTextField();
        btnCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar cuenta");
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 800));

        pnlFondo.setMaximumSize(new java.awt.Dimension(1200, 800));
        pnlFondo.setMinimumSize(new java.awt.Dimension(1200, 800));

        lblNombreCuenta.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblNombreCuenta.setForeground(new java.awt.Color(153, 153, 153));
        lblNombreCuenta.setText("Nombre de la cuenta:");

        txtFieldNombreCuenta.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldNombreCuenta.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldNombreCuenta.setText("Ingrese el nombre de su nueva cuenta");
        txtFieldNombreCuenta.setBorder(null);
        txtFieldNombreCuenta.setCaretPosition(5);
        txtFieldNombreCuenta.setPreferredSize(new java.awt.Dimension(27, 16));
        txtFieldNombreCuenta.setScrollOffset(0);
        txtFieldNombreCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldNombreCuentaFocusLost(evt);
            }
        });
        txtFieldNombreCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldNombreCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldNombreCuentaMouseExited(evt);
            }
        });
        txtFieldNombreCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNombreCuentaActionPerformed(evt);
            }
        });
        txtFieldNombreCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldNombreCuentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldNombreCuentaKeyTyped(evt);
            }
        });

        btnCrearCuenta.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.setToolTipText("");
        btnCrearCuenta.setBorderPainted(false);
        btnCrearCuenta.setContentAreaFilled(false);
        btnCrearCuenta.setMaximumSize(new java.awt.Dimension(113, 31));
        btnCrearCuenta.setMinimumSize(new java.awt.Dimension(113, 31));
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(lblNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(txtFieldNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(398, 398, 398))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(277, 277, 277)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        txtFieldNombreCuenta.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 900, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 400, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldNombreCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaActionPerformed
        // TODO add your handling code here:
        if (txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta"))
            txtFieldNombreCuenta.setText("");
    }//GEN-LAST:event_txtFieldNombreCuentaActionPerformed

    private void txtFieldNombreCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaFocusLost
        // TODO add your handling code here:
        if (txtFieldNombreCuenta.getText().equals("")) {
            txtFieldNombreCuenta.setText("Ingrese el nombre de su nueva cuenta");
        }
    }//GEN-LAST:event_txtFieldNombreCuentaFocusLost

    private void txtFieldNombreCuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaKeyReleased
        // TODO add your handling code here:
        txtFieldNombreCuenta.setText(txtFieldNombreCuenta.getText().trim());
    }//GEN-LAST:event_txtFieldNombreCuentaKeyReleased

    private void txtFieldNombreCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaKeyTyped
        // TODO add your handling code here:
        txtFieldNombreCuenta.setText(txtFieldNombreCuenta.getText().trim());
        if (txtFieldNombreCuenta.getText().length() >= 50) {
            evt.consume();
        }
        if (txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta")) {
            txtFieldNombreCuenta.setText("");
        }
    }//GEN-LAST:event_txtFieldNombreCuentaKeyTyped

    private void txtFieldNombreCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaMouseEntered
        // TODO add your handling code here:
        if (txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta"))
            txtFieldNombreCuenta.setText("");
    }//GEN-LAST:event_txtFieldNombreCuentaMouseEntered

    private void txtFieldNombreCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaMouseExited
        // TODO add your handling code here:
        if (txtFieldNombreCuenta.getText().equals("")) {
            txtFieldNombreCuenta.setText("Ingrese el nombre de su nueva cuenta");
        } else if (!txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta")) {
            evt.consume();
        }

    }//GEN-LAST:event_txtFieldNombreCuentaMouseExited

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        //SOLAMENTE ES PARA PROBAR QUE SE AGREGUE UNA CUENTA LOS DATOS ESTAN HARDCODEADOS
        //CuentasClientesRecord(int idCuentasClientes, Date fechaHoraApertura, String nombre,float saldo, int numCuenta, int idClientes ) 

        CuentasClientesRecord cuenta = new CuentasClientesRecord(0, null, txtFieldNombreCuenta.getText(), 0, null, cliente.getId());
        try {
            if (!txtFieldNombreCuenta.getText().equals("") && !txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta")) {
                this.clientesDao.insetarCuenta(cuenta, cliente);
                new Cuentas(clientesDao, cliente).setVisible(true);
                this.dispose();
            }
            new JOptionPane().showMessageDialog(this, "Cuenta creada exitosamente", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        } catch (PersistenciaException ex) {
            new JOptionPane().showMessageDialog(this, "La cuenta no fue registrada", "¡Aviso!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistroCuentasBancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistroCuentasBancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistroCuentasBancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistroCuentasBancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmRegistroCuentasBancarias().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JLabel lblNombreCuenta;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextField txtFieldNombreCuenta;
    // End of variables declaration//GEN-END:variables
}
