/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import dominio.Cliente;
import dominio.CuentasClientesRecord;
import excepciones.PersistenciaException;
import interfaces.IClientesDAO;
import interfaces.ICuentasClientesDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Elmer y Kim
 */
public class FrmRegistroCuentasBancarias extends javax.swing.JFrame {

    private final ICuentasClientesDAO clientesDao;
    private final Cliente cliente;

    /**
     * Creates new form FrmCuentasBancarias
     */
    public FrmRegistroCuentasBancarias(ICuentasClientesDAO clientesDao, Cliente cliente) {
        initComponents();
        this.clientesDao = clientesDao;
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRetiroSinCuenta = new javax.swing.JButton();
        lblNombreCuenta = new javax.swing.JLabel();
        txtFieldNombreCuenta = new javax.swing.JTextField();
        lblRecuadro = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar cuenta");
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 800));

        pnlFondo.setMaximumSize(new java.awt.Dimension(1200, 800));
        pnlFondo.setMinimumSize(new java.awt.Dimension(1200, 800));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnAceptar.png"))); // NOI18N
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnCancelar.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, -1, -1));

        btnRetiroSinCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRetiro.png"))); // NOI18N
        btnRetiroSinCuenta.setBorder(null);
        btnRetiroSinCuenta.setBorderPainted(false);
        btnRetiroSinCuenta.setContentAreaFilled(false);
        btnRetiroSinCuenta.setFocusable(false);
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRetiroSinCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 423, -1, -1));

        lblNombreCuenta.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblNombreCuenta.setForeground(new java.awt.Color(153, 153, 153));
        lblNombreCuenta.setText("Nombre de la cuenta:");
        pnlFondo.add(lblNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 180, -1));

        txtFieldNombreCuenta.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldNombreCuenta.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldNombreCuenta.setText("Ingrese el nombre de su nueva cuenta");
        txtFieldNombreCuenta.setBorder(null);
        txtFieldNombreCuenta.setCaretPosition(5);
        txtFieldNombreCuenta.setPreferredSize(new java.awt.Dimension(27, 16));
        txtFieldNombreCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldNombreCuentaFocusLost(evt);
            }
        });
        txtFieldNombreCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldNombreCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldNombreCuentaMouseExited(evt);
            }
        });
        txtFieldNombreCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNombreCuentaActionPerformed(evt);
            }
        });
        txtFieldNombreCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldNombreCuentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldNombreCuentaKeyTyped(evt);
            }
        });
        pnlFondo.add(txtFieldNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 290, 30));
        txtFieldNombreCuenta.getAccessibleContext().setAccessibleName("");

        lblRecuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recuadroWeb.png"))); // NOI18N
        lblRecuadro.setAlignmentY(0.0F);
        pnlFondo.add(lblRecuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.png"))); // NOI18N
        lblFondo.setAlignmentY(0.0F);
        lblFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 976, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldNombreCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaActionPerformed
        // TODO add your handling code here:
        if (txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta"))
            txtFieldNombreCuenta.setText("");
    }//GEN-LAST:event_txtFieldNombreCuentaActionPerformed

    private void txtFieldNombreCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaFocusLost
        // TODO add your handling code here:
        if (txtFieldNombreCuenta.getText().equals("")) {
            txtFieldNombreCuenta.setText("Ingrese el nombre de su nueva cuenta");
        }
    }//GEN-LAST:event_txtFieldNombreCuentaFocusLost

    private void txtFieldNombreCuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaKeyReleased
        // TODO add your handling code here:
        txtFieldNombreCuenta.setText(txtFieldNombreCuenta.getText().trim());
    }//GEN-LAST:event_txtFieldNombreCuentaKeyReleased

    private void txtFieldNombreCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaKeyTyped
        // TODO add your handling code here:
        txtFieldNombreCuenta.setText(txtFieldNombreCuenta.getText().trim());
        if (txtFieldNombreCuenta.getText().length() >= 50) {
            evt.consume();
        }
        if (txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta")) {
            txtFieldNombreCuenta.setText("");
        }
    }//GEN-LAST:event_txtFieldNombreCuentaKeyTyped

    private void txtFieldNombreCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaMouseEntered
        // TODO add your handling code here:
        if (txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta"))
            txtFieldNombreCuenta.setText("");
    }//GEN-LAST:event_txtFieldNombreCuentaMouseEntered

    private void txtFieldNombreCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNombreCuentaMouseExited
        // TODO add your handling code here:
        if (txtFieldNombreCuenta.getText().equals("")) {
            txtFieldNombreCuenta.setText("Ingrese el nombre de su nueva cuenta");
        } else if (!txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta")) {
            evt.consume();
        }

    }//GEN-LAST:event_txtFieldNombreCuentaMouseExited

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       // TODO add your handling code here:
        //SOLAMENTE ES PARA PROBAR QUE SE AGREGUE UNA CUENTA LOS DATOS ESTAN HARDCODEADOS
        //CuentasClientesRecord(int idCuentasClientes, Date fechaHoraApertura, String nombre,float saldo, int numCuenta, int idClientes ) 

           //IdCuentaClientes es Setteado a 0 ya que este id no es importante para la creación de la cuenta
        CuentasClientesRecord cuenta = new CuentasClientesRecord(0, null, txtFieldNombreCuenta.getText(), 0, null, cliente.getId());
        try {
            if (!txtFieldNombreCuenta.getText().equals("") && !txtFieldNombreCuenta.getText().equals("Ingrese el nombre de su nueva cuenta")) {
                this.clientesDao.insetarCuenta(cuenta, cliente);
                new FrmCuentas(clientesDao, cliente).setVisible(true);
                this.dispose();
            }
            new JOptionPane().showMessageDialog(this, "Cuenta creada exitosamente", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        } catch (PersistenciaException ex) {
            new JOptionPane().showMessageDialog(this, "La cuenta no fue registrada", "¡Aviso!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new FrmCuentas(this.clientesDao,this.cliente).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistroCuentasBancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistroCuentasBancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistroCuentasBancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistroCuentasBancarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmRegistroCuentasBancarias().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombreCuenta;
    private javax.swing.JLabel lblRecuadro;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextField txtFieldNombreCuenta;
    // End of variables declaration//GEN-END:variables
}
