/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import dominio.Cliente;
import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Label;
import java.sql.Date;

/**
 *
 * @author eruma
 */
public class Register extends javax.swing.JFrame {

    private Cliente cliente;
    private final IClientesDAO clientesDao;

    /**
     * Creates new form Login
     */
    public Register(IClientesDAO clientesDao) {
        initComponents();
        this.clientesDao = clientesDao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        txtFieldDia = new javax.swing.JTextField();
        txtFieldMes = new javax.swing.JTextField();
        txtFieldAno = new javax.swing.JTextField();
        btnRetiroSinCuenta = new javax.swing.JButton();
        txtFieldFechaNacimiento = new javax.swing.JTextField();
        txtFieldApellidoMat = new javax.swing.JTextField();
        txtFieldApellidoPat = new javax.swing.JTextField();
        txtFieldNombre = new javax.swing.JTextField();
        lblIconos = new javax.swing.JLabel();
        lblRecuadro = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        pnlFondo.setFocusable(false);
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atrasRegister.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasMouseEntered(evt);
            }
        });
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        pnlFondo.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        btnSig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaSig..png"))); // NOI18N
        btnSig.setBorder(null);
        btnSig.setBorderPainted(false);
        btnSig.setContentAreaFilled(false);
        btnSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSigMouseEntered(evt);
            }
        });
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });
        pnlFondo.add(btnSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, -1, -1));

        txtFieldDia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldDia.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldDia.setText("Día");
        txtFieldDia.setBorder(null);
        txtFieldDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldDiaFocusLost(evt);
            }
        });
        txtFieldDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldDiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldDiaMouseExited(evt);
            }
        });
        txtFieldDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDiaActionPerformed(evt);
            }
        });
        txtFieldDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldDiaKeyTyped(evt);
            }
        });
        pnlFondo.add(txtFieldDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 424, 40, -1));

        txtFieldMes.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldMes.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldMes.setText("Mes");
        txtFieldMes.setBorder(null);
        txtFieldMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldMesFocusLost(evt);
            }
        });
        txtFieldMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldMesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldMesMouseExited(evt);
            }
        });
        txtFieldMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldMesActionPerformed(evt);
            }
        });
        txtFieldMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldMesKeyTyped(evt);
            }
        });
        pnlFondo.add(txtFieldMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 424, 40, -1));

        txtFieldAno.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldAno.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldAno.setText("Año");
        txtFieldAno.setBorder(null);
        txtFieldAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldAnoFocusLost(evt);
            }
        });
        txtFieldAno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldAnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldAnoMouseExited(evt);
            }
        });
        txtFieldAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAnoActionPerformed(evt);
            }
        });
        txtFieldAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldAnoKeyTyped(evt);
            }
        });
        pnlFondo.add(txtFieldAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 424, 40, -1));

        btnRetiroSinCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRetiro.png"))); // NOI18N
        btnRetiroSinCuenta.setBorder(null);
        btnRetiroSinCuenta.setBorderPainted(false);
        btnRetiroSinCuenta.setContentAreaFilled(false);
        btnRetiroSinCuenta.setFocusable(false);
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRetiroSinCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 423, -1, -1));

        txtFieldFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldFechaNacimiento.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldFechaNacimiento.setText("Fecha Nacimiento");
        txtFieldFechaNacimiento.setBorder(null);
        txtFieldFechaNacimiento.setFocusable(false);
        txtFieldFechaNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldFechaNacimientoFocusLost(evt);
            }
        });
        txtFieldFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldFechaNacimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldFechaNacimientoMouseExited(evt);
            }
        });
        txtFieldFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldFechaNacimientoActionPerformed(evt);
            }
        });
        txtFieldFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldFechaNacimientoKeyTyped(evt);
            }
        });
        pnlFondo.add(txtFieldFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 424, 100, -1));

        txtFieldApellidoMat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldApellidoMat.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldApellidoMat.setText("Apellido Mat.");
        txtFieldApellidoMat.setBorder(null);
        txtFieldApellidoMat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldApellidoMatFocusLost(evt);
            }
        });
        txtFieldApellidoMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldApellidoMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldApellidoMatMouseExited(evt);
            }
        });
        txtFieldApellidoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldApellidoMatActionPerformed(evt);
            }
        });
        txtFieldApellidoMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldApellidoMatKeyTyped(evt);
            }
        });
        pnlFondo.add(txtFieldApellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 378, 310, -1));

        txtFieldApellidoPat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldApellidoPat.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldApellidoPat.setText("Apellido Pat.");
        txtFieldApellidoPat.setBorder(null);
        txtFieldApellidoPat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldApellidoPatFocusLost(evt);
            }
        });
        txtFieldApellidoPat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldApellidoPatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldApellidoPatMouseExited(evt);
            }
        });
        txtFieldApellidoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldApellidoPatActionPerformed(evt);
            }
        });
        txtFieldApellidoPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldApellidoPatKeyTyped(evt);
            }
        });
        pnlFondo.add(txtFieldApellidoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 334, 310, -1));

        txtFieldNombre.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtFieldNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldNombre.setText("Nombre");
        txtFieldNombre.setBorder(null);
        txtFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldNombreFocusLost(evt);
            }
        });
        txtFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldNombreMouseExited(evt);
            }
        });
        txtFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNombreActionPerformed(evt);
            }
        });
        txtFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldNombreKeyTyped(evt);
            }
        });
        pnlFondo.add(txtFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 310, -1));

        lblIconos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIconos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lineaCredenciales.png"))); // NOI18N
        pnlFondo.add(lblIconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblRecuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recuadroWeb.png"))); // NOI18N
        lblRecuadro.setAlignmentY(0.0F);
        pnlFondo.add(lblRecuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.png"))); // NOI18N
        lblFondo.setAlignmentY(0.0F);
        lblFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNombreActionPerformed

    }//GEN-LAST:event_txtFieldNombreActionPerformed

    private void txtFieldNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNombreMouseEntered
        if (txtFieldNombre.getText().equals("Nombre"))
            txtFieldNombre.setText("");
    }//GEN-LAST:event_txtFieldNombreMouseEntered

    private void txtFieldNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNombreMouseExited
        if (txtFieldNombre.getText().equals("")) {
            txtFieldNombre.setText("Nombre");
        } else if (!txtFieldNombre.getText().equals("Nombre")) {
            evt.consume();
        }

    }//GEN-LAST:event_txtFieldNombreMouseExited

    private void txtFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldNombreFocusLost
        if (txtFieldNombre.getText().equals("")) {
            txtFieldNombre.setText("Nombre");
        }
    }//GEN-LAST:event_txtFieldNombreFocusLost

    private void txtFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldNombreKeyTyped
        if (txtFieldNombre.getText().length() >= 50) {
            evt.consume();
        }

        if (txtFieldNombre.getText().equals("Nombre")) {
            txtFieldNombre.setText("");
        }
    }//GEN-LAST:event_txtFieldNombreKeyTyped

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed

    private void txtFieldApellidoPatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldApellidoPatFocusLost
        if (txtFieldApellidoPat.getText().equals("")) {
            txtFieldApellidoPat.setText("Apellido Pat.");
        }
    }//GEN-LAST:event_txtFieldApellidoPatFocusLost

    private void txtFieldApellidoPatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldApellidoPatMouseEntered
        if (txtFieldApellidoPat.getText().equals("Apellido Pat."))
            txtFieldApellidoPat.setText("");
    }//GEN-LAST:event_txtFieldApellidoPatMouseEntered

    private void txtFieldApellidoPatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldApellidoPatMouseExited
        if (txtFieldApellidoPat.getText().equals("")) {
            txtFieldApellidoPat.setText("Apellido Pat.");
        } else if (!txtFieldApellidoPat.getText().equals("Apellido Pat.")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldApellidoPatMouseExited

    private void txtFieldApellidoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldApellidoPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldApellidoPatActionPerformed

    private void txtFieldApellidoPatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldApellidoPatKeyTyped
        if (txtFieldApellidoPat.getText().length() >= 50) {
            evt.consume();
        }
        if (txtFieldApellidoPat.getText().equals("Apellido Pat.")) {
            txtFieldApellidoPat.setText("");
        }
    }//GEN-LAST:event_txtFieldApellidoPatKeyTyped

    private void txtFieldApellidoMatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldApellidoMatFocusLost
        if (txtFieldApellidoMat.getText().equals("")) {
            txtFieldApellidoMat.setText("Apellido Mat.");
        }
    }//GEN-LAST:event_txtFieldApellidoMatFocusLost

    private void txtFieldApellidoMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldApellidoMatMouseEntered
        if (txtFieldApellidoMat.getText().equals("Apellido Mat."))
            txtFieldApellidoMat.setText("");
    }//GEN-LAST:event_txtFieldApellidoMatMouseEntered

    private void txtFieldApellidoMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldApellidoMatMouseExited
        if (txtFieldApellidoMat.getText().equals("")) {
            txtFieldApellidoMat.setText("Apellido Mat.");
        } else if (!txtFieldApellidoMat.getText().equals("Apellido Mat.")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldApellidoMatMouseExited

    private void txtFieldApellidoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldApellidoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldApellidoMatActionPerformed

    private void txtFieldApellidoMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldApellidoMatKeyTyped
        if(txtFieldApellidoMat.getText().length()>=50) evt.consume();
        if (txtFieldApellidoMat.getText().equals("Apellido Mat.")) {
            txtFieldApellidoMat.setText("");
        }
    }//GEN-LAST:event_txtFieldApellidoMatKeyTyped

    private void txtFieldFechaNacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldFechaNacimientoFocusLost

    }//GEN-LAST:event_txtFieldFechaNacimientoFocusLost

    private void txtFieldFechaNacimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldFechaNacimientoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFechaNacimientoMouseEntered

    private void txtFieldFechaNacimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldFechaNacimientoMouseExited

    }//GEN-LAST:event_txtFieldFechaNacimientoMouseExited

    private void txtFieldFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFechaNacimientoActionPerformed

    private void txtFieldFechaNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldFechaNacimientoKeyTyped

    }//GEN-LAST:event_txtFieldFechaNacimientoKeyTyped

    private void txtFieldAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldAnoFocusLost
        if (txtFieldAno.getText().equals("")) {
            txtFieldAno.setText("Año");
        }
    }//GEN-LAST:event_txtFieldAnoFocusLost

    private void txtFieldAnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldAnoMouseEntered
        if (txtFieldAno.getText().equals("Año"))
            txtFieldAno.setText("");
    }//GEN-LAST:event_txtFieldAnoMouseEntered

    private void txtFieldAnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldAnoMouseExited
        if (txtFieldAno.getText().equals("")) {
            txtFieldAno.setText("Año");
        } else if (!txtFieldAno.getText().equals("Año")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldAnoMouseExited

    private void txtFieldAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAnoActionPerformed

    private void txtFieldAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldAnoKeyTyped
        if (txtFieldAno.getText().length() >= 4) {
            evt.consume();
        }

        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txtFieldAno.getText().equals("Año")) {
            txtFieldAno.setText("");
        }
    }//GEN-LAST:event_txtFieldAnoKeyTyped

    private void txtFieldMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldMesFocusLost
        if (txtFieldMes.getText().equals("")) {
            txtFieldMes.setText("Mes");
        }
    }//GEN-LAST:event_txtFieldMesFocusLost

    private void txtFieldMesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldMesMouseEntered
        if (txtFieldMes.getText().equals("Mes"))
            txtFieldMes.setText("");
    }//GEN-LAST:event_txtFieldMesMouseEntered

    private void txtFieldMesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldMesMouseExited
        if (txtFieldMes.getText().equals("")) {
            txtFieldMes.setText("Mes");
        } else if (!txtFieldMes.getText().equals("Mes")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldMesMouseExited

    private void txtFieldMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldMesActionPerformed

    private void txtFieldMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldMesKeyTyped

        if (txtFieldMes.getText().length() >= 2) {
            evt.consume();
        }

        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txtFieldMes.getText().equals("Mes")) {
            txtFieldMes.setText("");
        }
    }//GEN-LAST:event_txtFieldMesKeyTyped

    private void txtFieldDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDiaFocusLost
        if (txtFieldDia.getText().equals("")) {
            txtFieldDia.setText("Dia");
        }
    }//GEN-LAST:event_txtFieldDiaFocusLost

    private void txtFieldDiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldDiaMouseEntered

        if (txtFieldDia.getText().equals("Día"))
            txtFieldDia.setText("");
    }//GEN-LAST:event_txtFieldDiaMouseEntered

    private void txtFieldDiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldDiaMouseExited
        if (txtFieldDia.getText().equals("")) {
            txtFieldDia.setText("Día");
        } else if (!txtFieldDia.getText().equals("Día")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldDiaMouseExited

    private void txtFieldDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDiaActionPerformed

    private void txtFieldDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldDiaKeyTyped
        if (txtFieldDia.getText().length() >= 2) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txtFieldDia.getText().equals("Día")) {
            txtFieldDia.setText("");
        }
    }//GEN-LAST:event_txtFieldDiaKeyTyped

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        int ano = Integer.parseInt(this.txtFieldAno.getText()) - 1900;
        int mes = Integer.parseInt(this.txtFieldMes.getText()) - 1;
        int dia = Integer.parseInt(this.txtFieldDia.getText());

        Date fechaNacimiento = new Date(ano, mes, dia);

        this.cliente = new Cliente(fechaNacimiento, this.txtFieldNombre.getText(), this.txtFieldApellidoPat.getText(), this.txtFieldApellidoMat.getText());
        new Register2(cliente, this.clientesDao).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSigActionPerformed

    private void btnSigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSigMouseEntered

    }//GEN-LAST:event_btnSigMouseEntered

    private void btnAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasMouseEntered

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        new Login(this.clientesDao).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JButton btnSig;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIconos;
    private javax.swing.JLabel lblRecuadro;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextField txtFieldAno;
    private javax.swing.JTextField txtFieldApellidoMat;
    private javax.swing.JTextField txtFieldApellidoPat;
    private javax.swing.JTextField txtFieldDia;
    private javax.swing.JTextField txtFieldFechaNacimiento;
    private javax.swing.JTextField txtFieldMes;
    private javax.swing.JTextField txtFieldNombre;
    // End of variables declaration//GEN-END:variables
}
